apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30008 # Use a specific NodePort, or omit this line to have Kubernetes allocate a random port
  selector:
    app: mysql
  type: NodePort
